name: trigger

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: pr check running for branch:<branch name>
        run: echo "PR check running for branch:${{ github.head_ref }}"
